version: '2.1'
services:
  nginx:
    image: nginx:1.15-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d
      - ./data/certs:/certs
    restart: always
    command: "sh -c '/usr/sbin/nginx && nc -v -l -p 12345 -e nginx -s reload'"
  certbot:
    build:
      context: certbot
      dockerfile: Dockerfile
    container_name: certbot
    ports:
      - 81:80
    volumes:
      - ./data/certs:/certs
      - ./data/certbot/letsencrypt:/etc/letsencrypt
      - ./data/certbot/var_log_letsencrypt:/var/log/letsencrypt
    environment:
      - LOGFILE=/var/log/letsencrypt/certrenewal.log
      - DEBUG=false
      - STAGING=true
      - HEALTH_CHECK_URL=${DOCKER_REGISTRY_DOMAIN_NAME}:80
      - DOMAINS=${DOCKER_REGISTRY_DOMAIN_NAME}
      - EMAIL=daniel.schroeder@smail.inf.h-brs.de
      - RENEWED_CERTS_HOOK=echo "1" | nc nginx 12345
  registry:
    image: registry:2
    ports:
      - 5000:5000
    environment:
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/${DOCKER_REGISTRY_DOMAIN_NAME}.fullchain.pem
      - REGISTRY_HTTP_TLS_KEY=/certs/${DOCKER_REGISTRY_DOMAIN_NAME}.key.pem
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
      - FORCE_SSL=1
    volumes:
      - ./data/registry:/var/lib/registry
      - ./data/certs:/certs
      - ./conf/auth:/auth
    restart: always
  registryui:
    image: konradkleine/docker-registry-frontend:v2
    ports:
      - 444:443
    environment:
      - ENV_DOCKER_REGISTRY_HOST=${DOCKER_REGISTRY_DOMAIN_NAME}
      - ENV_DOCKER_REGISTRY_PORT=5000
      - ENV_DOCKER_REGISTRY_USE_SSL=1
    restart: always